class ApplicationRecord < ActiveRecord::Base
end
class PersonLocation::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Location::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PersonAffiliation::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Affiliation::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Person::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ActiveRecord::Associations::CollectionProxy < ActiveRecord::Relation
end
class ActiveRecord::Relation < Object
end
module ActiveRecord::Associations
end
