# TypeProf 0.21.7

# Classes
class Importer
  @file: untyped
  @data_list: Array[{person: untyped, locations: Array[String], affiliations: Array[String]}]
  @csv: Array[Array[String?]]?

  def initialize: (untyped file) -> void
  def run: -> Array[{person: untyped, locations: Array[String], affiliations: Array[String]}]
  def insert_to_db!: ({person: untyped, locations: Array[String], affiliations: Array[String]} data) -> untyped
  def build_person: (Array[String?] row) -> untyped
  def build_location: (Array[String?] row) -> Array[String]
  def build_affiliation: (Array[String?] row) -> Array[String]
  def csv: -> Array[Array[String?]]?
end
